# Generated by Django 5.2.5 on 2025-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
