# Generated by Django 5.2.4 on 2025-09-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
